// GENERATED by tools/board_gen.py from Software/boards/*.yaml - do not edit.
// Rebuild with `python3 tools/board_gen.py`; CI fails if this file and the
// declarations disagree.
//
// What each board can do, as the union of the features its declaration
// carries. This is the tie between the board schema and the registries that
// gate rows on hardware: a row asks for a capability, and the answer comes
// from the same file that already says which pins the feature uses, so a
// board cannot advertise a feature it has no pins for.
//
// Ids are compile-time only - never stored, never sent - so they may be
// renumbered freely. The generator preserves the order it already emitted
// anyway, so that declaring a new feature is one added line here.

#ifndef BE_DEVBOARD_HAL_CAPABILITIES_H
#define BE_DEVBOARD_HAL_CAPABILITIES_H

#include <stdint.h>

enum class BoardCap : uint8_t {
  None = 0,  // "no requirement on this axis", so it is never a board's capability
  Rs485,
  Can,
  Chademo,
  Contactors,
  PrechargeAuto,
  Sma,
  SdMmc,
  SdCard,
  SdSpi,
  RgbLed,
  EquipmentStop,
  BatteryWakeup,
  ApButton,
  DisplayI2c,
  Ethernet,
  Count,
};

inline constexpr uint8_t BOARD_CAP_COUNT = static_cast<uint8_t>(BoardCap::Count);

// The sets below are bitmasks, so the whole enum has to fit one word.
static_assert(BOARD_CAP_COUNT <= 64, "BoardCap has outgrown the 64-bit capability set");

constexpr uint64_t board_cap_bit(BoardCap cap) {
  return cap == BoardCap::None ? uint64_t{0} : (uint64_t{1} << static_cast<uint8_t>(cap));
}

// Per-board capability sets. Constant expressions on purpose: a per-board
// build folds a requirement check away entirely, so a row gated off on this
// board costs it nothing.
inline constexpr uint64_t BOARD_CAPS_3LB =
    board_cap_bit(BoardCap::Rs485) |
    board_cap_bit(BoardCap::Can) |
    board_cap_bit(BoardCap::Chademo) |
    board_cap_bit(BoardCap::Contactors) |
    board_cap_bit(BoardCap::PrechargeAuto) |
    board_cap_bit(BoardCap::Sma) |
    board_cap_bit(BoardCap::RgbLed) |
    board_cap_bit(BoardCap::EquipmentStop) |
    board_cap_bit(BoardCap::BatteryWakeup);
inline constexpr uint64_t BOARD_CAPS_BECOM =
    board_cap_bit(BoardCap::Rs485) |
    board_cap_bit(BoardCap::Can) |
    board_cap_bit(BoardCap::Contactors) |
    board_cap_bit(BoardCap::PrechargeAuto) |
    board_cap_bit(BoardCap::Sma) |
    board_cap_bit(BoardCap::RgbLed) |
    board_cap_bit(BoardCap::EquipmentStop) |
    board_cap_bit(BoardCap::BatteryWakeup) |
    board_cap_bit(BoardCap::ApButton);
inline constexpr uint64_t BOARD_CAPS_DEVKIT =
    board_cap_bit(BoardCap::Rs485) |
    board_cap_bit(BoardCap::Can) |
    board_cap_bit(BoardCap::Contactors) |
    board_cap_bit(BoardCap::PrechargeAuto) |
    board_cap_bit(BoardCap::Sma) |
    board_cap_bit(BoardCap::RgbLed) |
    board_cap_bit(BoardCap::EquipmentStop) |
    board_cap_bit(BoardCap::BatteryWakeup) |
    board_cap_bit(BoardCap::ApButton);
inline constexpr uint64_t BOARD_CAPS_DFROBOT_EDGE101 =
    board_cap_bit(BoardCap::Rs485) |
    board_cap_bit(BoardCap::Can) |
    board_cap_bit(BoardCap::SdSpi) |
    board_cap_bit(BoardCap::SdCard) |
    board_cap_bit(BoardCap::RgbLed) |
    board_cap_bit(BoardCap::ApButton) |
    board_cap_bit(BoardCap::Ethernet);
inline constexpr uint64_t BOARD_CAPS_LILYGO =
    board_cap_bit(BoardCap::Rs485) |
    board_cap_bit(BoardCap::Can) |
    board_cap_bit(BoardCap::Chademo) |
    board_cap_bit(BoardCap::Contactors) |
    board_cap_bit(BoardCap::PrechargeAuto) |
    board_cap_bit(BoardCap::Sma) |
    board_cap_bit(BoardCap::SdMmc) |
    board_cap_bit(BoardCap::SdCard) |
    board_cap_bit(BoardCap::RgbLed) |
    board_cap_bit(BoardCap::EquipmentStop) |
    board_cap_bit(BoardCap::BatteryWakeup) |
    board_cap_bit(BoardCap::ApButton) |
    board_cap_bit(BoardCap::DisplayI2c);
inline constexpr uint64_t BOARD_CAPS_LILYGO2CAN =
    board_cap_bit(BoardCap::Rs485) |
    board_cap_bit(BoardCap::Can) |
    board_cap_bit(BoardCap::Chademo) |
    board_cap_bit(BoardCap::Contactors) |
    board_cap_bit(BoardCap::PrechargeAuto) |
    board_cap_bit(BoardCap::Sma) |
    board_cap_bit(BoardCap::RgbLed) |
    board_cap_bit(BoardCap::EquipmentStop) |
    board_cap_bit(BoardCap::BatteryWakeup) |
    board_cap_bit(BoardCap::ApButton) |
    board_cap_bit(BoardCap::DisplayI2c);
inline constexpr uint64_t BOARD_CAPS_STARK =
    board_cap_bit(BoardCap::Rs485) |
    board_cap_bit(BoardCap::Can) |
    board_cap_bit(BoardCap::Contactors) |
    board_cap_bit(BoardCap::PrechargeAuto) |
    board_cap_bit(BoardCap::Sma) |
    board_cap_bit(BoardCap::RgbLed) |
    board_cap_bit(BoardCap::EquipmentStop) |
    board_cap_bit(BoardCap::BatteryWakeup) |
    board_cap_bit(BoardCap::ApButton);
inline constexpr uint64_t BOARD_CAPS_WAVESHARE =
    board_cap_bit(BoardCap::Rs485) |
    board_cap_bit(BoardCap::Can) |
    board_cap_bit(BoardCap::Contactors) |
    board_cap_bit(BoardCap::PrechargeAuto) |
    board_cap_bit(BoardCap::Sma) |
    board_cap_bit(BoardCap::RgbLed) |
    board_cap_bit(BoardCap::EquipmentStop) |
    board_cap_bit(BoardCap::BatteryWakeup) |
    board_cap_bit(BoardCap::ApButton) |
    board_cap_bit(BoardCap::DisplayI2c);

// The active board's set, where the build has exactly one board - the same
// macro hal.cpp switches on. A build that compiles every board (one image
// for all of them) matches no branch and leaves this undefined, which is the
// signal to bind the set at runtime from the board that was selected.
#if defined(HW_3LB)
#define BE_BOARD_CAPS BOARD_CAPS_3LB
#elif defined(HW_BECOM)
#define BE_BOARD_CAPS BOARD_CAPS_BECOM
#elif defined(HW_DEVKIT)
#define BE_BOARD_CAPS BOARD_CAPS_DEVKIT
#elif defined(HW_DFROBOT_EDGE101)
#define BE_BOARD_CAPS BOARD_CAPS_DFROBOT_EDGE101
#elif defined(HW_LILYGO)
#define BE_BOARD_CAPS BOARD_CAPS_LILYGO
#elif defined(HW_LILYGO2CAN)
#define BE_BOARD_CAPS BOARD_CAPS_LILYGO2CAN
#elif defined(HW_STARK)
#define BE_BOARD_CAPS BOARD_CAPS_STARK
#elif defined(HW_WAVESHARE)
#define BE_BOARD_CAPS BOARD_CAPS_WAVESHARE
#endif

#endif  // BE_DEVBOARD_HAL_CAPABILITIES_H
