#!/usr/bin/env python3
"""Generate the board pin fragments from Software/boards/*.yaml.

Emits Software/src/devboard/hal/generated/<board>_pins.inc - a fragment of
class members that the hand-written board header includes inside its class
body. Fragments rather than whole headers because four of the seven boards
also have getters that select a pin from a runtime user setting; those stay
hand-written, and generating around them would mean encoding the settings
logic here, which stage 1 defers.

No PyYAML: this repo has no Python dependencies (CI runs stdlib scripts and
pip-installs only platformio). The parser below accepts the small subset these
files use and REFUSES anything else rather than guessing - a declaration that
silently parses wrong would produce a wrong pin map, which is the failure this
tooling exists to prevent.

Usage: python3 tools/board_gen.py           regenerate fragments
       python3 tools/board_gen.py --check   fail if anything is out of date
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).parent.parent
BOARDS = ROOT / 'Software' / 'boards'
OUT = ROOT / 'Software' / 'src' / 'devboard' / 'hal' / 'generated'

BANNER = ('// GENERATED by tools/board_gen.py from Software/boards/{board}.yaml\n'
          '// Do not edit: edit the board declaration and regenerate.\n'
          '// Included inside the board class body; pins that depend on a runtime\n'
          '// user setting are hand-written in the board header, not here.\n')


def parse_yaml_subset(text, where):
    """Scalars, one nested map (pins:), and one nested map of inline maps
    (scalars:). Anything else is an error, not a guess."""
    data, section = {}, None
    for n, raw in enumerate(text.splitlines(), 1):
        line = raw.split('#', 1)[0].rstrip() if not raw.lstrip().startswith('#') else ''
        if not line.strip():
            continue
        indent = len(line) - len(line.lstrip())
        body = line.strip()
        if indent == 0:
            if not body.endswith(':') and ':' not in body:
                sys.exit(f'{where}:{n}: cannot parse "{body}"')
            key, _, value = body.partition(':')
            key, value = key.strip(), value.strip()
            if value == '':
                section = key
                data[key] = {}
            else:
                section = None
                data[key] = value.strip('"')
        elif indent == 2 and section:
            key, _, value = body.partition(':')
            data[section][key.strip()] = value.strip()
        else:
            sys.exit(f'{where}:{n}: unexpected indent {indent} in "{body}"')
    return data


def fragment(board, data):
    lines = [BANNER.format(board=board), '']
    lines.append(f'  const char* name() {{ return "{data["name"]}"; }}')
    lines.append('')
    for role, num in data.get('pins', {}).items():
        lines.append(f'  virtual gpio_num_t {role}() {{ return GPIO_NUM_{num}; }}')
    for name, spec in data.get('scalars', {}).items():
        m = re.match(r'\{type:\s*(\w+),\s*value:\s*"([^"]*)"\}', spec)
        if not m:
            sys.exit(f'{board}: cannot parse scalar "{name}: {spec}"')
        lines.append(f'  virtual {m.group(1)} {name}() {{ return {m.group(2)}; }}')
    return '\n'.join(lines) + '\n'


def main():
    check = '--check' in sys.argv
    OUT.mkdir(parents=True, exist_ok=True)
    stale = []
    for path in sorted(BOARDS.glob('*.yaml')):
        data = parse_yaml_subset(path.read_text(encoding='utf-8'), path.name)
        board = data['board']
        text = fragment(board, data)
        target = OUT / f'{board}_pins.inc'
        if check:
            if not target.exists() or target.read_text(encoding='utf-8') != text:
                stale.append(target.relative_to(ROOT).as_posix())
        else:
            target.write_text(text, encoding='utf-8')
            print(f'{board:12} -> {target.relative_to(ROOT).as_posix()}')
    if check:
        if stale:
            print('generated fragments are out of date:')
            print('\n'.join('  ' + s for s in stale))
            print('run: python3 tools/board_gen.py')
            sys.exit(1)
        print('board fragments: up to date')


if __name__ == '__main__':
    main()
