#!/usr/bin/env python3
"""Generate the board fragments from Software/boards/*.yaml.

Emits, per board, into Software/src/devboard/hal/generated/:
  <board>_pins.inc   class members, included inside the board class body
  <board>_caps.inc   BOARD_HAS_* defines, included at file scope

Fragments rather than whole headers because several boards also have getters
that pick a pin from a runtime user setting or a hardware variant; those stay
hand-written, and generating around them would mean encoding that logic here,
which stage 1 defers.

No PyYAML: this repo has no Python dependencies (CI runs stdlib scripts and
pip-installs only platformio). The parser below accepts the small subset these
files use and REFUSES anything else rather than guessing - a declaration that
silently parses wrong would produce a wrong pin map, which is the failure this
tooling exists to prevent.

Every declared capability and CAN slot is validated against the board's pin
map before anything is written: a capability whose driver needs a pin the
board does not define is an error naming board, capability and missing role.
The required-role tables below are transcribed from the driver sources that
actually read the pins (comm_can.cpp, sdcard.cpp, display.cpp, ...), not from
the role names, because the two disagree in places - see SD_CS_PIN.

Usage: python3 tools/board_gen.py            regenerate fragments
       python3 tools/board_gen.py --check    fail if anything is out of date
       python3 tools/board_gen.py --boards DIR --out DIR    (for tests)
"""
import sys
from pathlib import Path

ROOT = Path(__file__).parent.parent
BOARDS = ROOT / 'Software' / 'boards'
OUT = ROOT / 'Software' / 'src' / 'devboard' / 'hal' / 'generated'

PINS_BANNER = ('// GENERATED by tools/board_gen.py from Software/boards/{board}.yaml\n'
               '// Do not edit: edit the board declaration and regenerate.\n'
               '// Included inside the board class body; pins that depend on a runtime\n'
               '// user setting are hand-written in the board header, not here.\n')

CAPS_BANNER = ('// GENERATED by tools/board_gen.py from Software/boards/{board}.yaml\n'
               '// Do not edit: edit the board declaration and regenerate.\n'
               '// Included at file scope. Each define means the board declares the\n'
               '// hardware AND the pins its driver needs are defined - checked at\n'
               '// generation time, so these are contracts rather than assertions.\n')

# Which pin roles each driver actually reads, transcribed from the source that
# reads them. 'requires' must resolve to a real GPIO; 'optional' may be absent
# or NC (the driver guards it); 'one_of' means at least one listed group must
# be fully present.
DRIVER_SPECS = {
    # comm_can.cpp init_CAN(), native TWAI section
    'native': {
        'requires': ['CAN_TX_PIN', 'CAN_RX_PIN'],
        'optional': ['CAN_SE_PIN'],
    },
    # comm_can.cpp CAN_ADDON_MCP2515: all five go to one alloc_pins() call
    'mcp2515': {
        'requires': ['MCP2515_SCK', 'MCP2515_MISO', 'MCP2515_MOSI', 'MCP2515_CS', 'MCP2515_INT'],
        'optional': ['MCP2515_RST'],  # driven only when != NC
    },
    # comm_can.cpp CANFD_NATIVE / CANFD_ADDON_MCP2518 - the same code path and
    # the same chip; "native" here means soldered on the board, not an ESP32
    # peripheral. Interrupt is INT, or INT0+INT1 when the part is wired that way.
    'mcp2518fd': {
        'requires': ['MCP2517_SCK', 'MCP2517_SDI', 'MCP2517_SDO', 'MCP2517_CS'],
        'one_of': [['MCP2517_INT'], ['MCP2517_INT0', 'MCP2517_INT1']],
    },
    # comm_can.cpp CANFD_ADDON_MCP2518_2: own CS+INT always; the SPI bus pins
    # only when it is on a different bus than the first chip, otherwise it
    # reuses that bus. Which one applies is decided by the declared bus scalars.
    'mcp2518fd_2': {
        'requires': ['MCP2517_CS2', 'MCP2517_INT2'],
        'shared_bus': ['MCP2517_SCK', 'MCP2517_SDI', 'MCP2517_SDO'],
        'own_bus': ['MCP2517_SCK2', 'MCP2517_SDI2', 'MCP2517_SDO2'],
    },
}

# Bare capability flags -> the roles their consumer reads.
CAP_SPECS = {
    'rs485': {'requires': ['RS485_TX_PIN', 'RS485_RX_PIN'],
              'optional': ['RS485_EN_PIN', 'RS485_SE_PIN', 'RS485_DE_PIN', 'PIN_5V_EN']},
    'modbus': {'requires': ['RS485_TX_PIN', 'RS485_RX_PIN']},
    # sdcard.cpp init_sdcard(): SD_MMC 1-bit, allocates MISO/MOSI/SCLK only.
    # SD_CS_PIN is declared by two boards and read by nothing - deliberately
    # not required here, because requiring it would encode a role name rather
    # than what the driver does.
    'sd_mmc': {'requires': ['SD_MISO_PIN', 'SD_MOSI_PIN', 'SD_SCLK_PIN'],
               'optional': ['SD_CS_PIN']},
    'display_i2c': {'requires': ['DISPLAY_SDA_PIN', 'DISPLAY_SCL_PIN']},
    'rgb_led': {'requires': ['LED_PIN']},
    'equipment_stop': {'requires': ['EQUIPMENT_STOP_PIN']},
    'ap_button': {'requires': ['AP_BUTTON_PIN']},
    'chademo': {'requires': ['CHADEMO_PIN_2', 'CHADEMO_PIN_10', 'CHADEMO_PIN_7',
                             'CHADEMO_PIN_4', 'CHADEMO_LOCK'],
                'optional': ['CHADEMO_CT_PIN']},
    'contactor_control': {'requires': ['POSITIVE_CONTACTOR_PIN', 'NEGATIVE_CONTACTOR_PIN', 'PRECHARGE_PIN']},
    'second_battery': {'requires': ['SECOND_BATTERY_CONTACTORS_PIN']},
    'third_battery': {'requires': ['TRIPLE_BATTERY_CONTACTORS_PIN']},
    'battery_wakeup': {'requires': ['WUP_PIN1', 'WUP_PIN2']},
    'automatic_precharge': {'requires': ['HIA4V1_PIN', 'INVERTER_DISCONNECT_CONTACTOR_PIN']},
    'sma_contactor': {'requires': ['INVERTER_CONTACTOR_ENABLE_PIN'],
                      'optional': ['INVERTER_CONTACTOR_ENABLE_LED_PIN']},
    'bms_power_control': {'requires': ['BMS_POWER']},
}


class DeclError(Exception):
    pass


def _split_top(text, sep=','):
    """Split on sep, ignoring separators inside double quotes."""
    parts, cur, quoted = [], '', False
    for ch in text:
        if ch == '"':
            quoted = not quoted
        if ch == sep and not quoted:
            parts.append(cur)
            cur = ''
        else:
            cur += ch
    parts.append(cur)
    return [p.strip() for p in parts if p.strip()]


def parse_inline_map(text, where):
    if not (text.startswith('{') and text.endswith('}')):
        raise DeclError(f'{where}: expected an inline map, got "{text}"')
    out = {}
    for item in _split_top(text[1:-1]):
        key, sep, value = item.partition(':')
        if not sep:
            raise DeclError(f'{where}: "{item}" is not key: value')
        out[key.strip()] = value.strip().strip('"')
    return out


def parse_yaml_subset(text, where):
    """Accepts exactly: top-level scalars, top-level inline lists, one level of
    nested "key: value" maps, and one level of nested "- {inline map}" lists."""
    data, section, kind = {}, None, None
    for n, raw in enumerate(text.splitlines(), 1):
        line = '' if raw.lstrip().startswith('#') else raw.split('#', 1)[0].rstrip()
        if not line.strip():
            continue
        indent = len(line) - len(line.lstrip())
        body = line.strip()
        if indent == 0:
            key, sep, value = body.partition(':')
            if not sep:
                raise DeclError(f'{where}:{n}: cannot parse "{body}"')
            key, value = key.strip(), value.strip()
            if value == '':
                section, kind, data[key] = key, None, None
            elif value.startswith('['):
                if not value.endswith(']'):
                    raise DeclError(f'{where}:{n}: unterminated list "{value}"')
                section, kind = None, None
                data[key] = _split_top(value[1:-1])
            else:
                section, kind = None, None
                data[key] = value.strip('"')
        elif indent == 2 and section:
            if body.startswith('- '):
                if kind is None:
                    kind, data[section] = 'list', []
                if kind != 'list':
                    raise DeclError(f'{where}:{n}: list item inside a map section "{section}"')
                data[section].append(parse_inline_map(body[2:].strip(), f'{where}:{n}'))
            else:
                if kind is None:
                    kind, data[section] = 'map', {}
                if kind != 'map':
                    raise DeclError(f'{where}:{n}: map entry inside a list section "{section}"')
                key, sep, value = body.partition(':')
                if not sep:
                    raise DeclError(f'{where}:{n}: cannot parse "{body}"')
                value = value.strip()
                data[section][key.strip()] = (parse_inline_map(value, f'{where}:{n}')
                                              if value.startswith('{') else value)
        else:
            raise DeclError(f'{where}:{n}: unexpected indent {indent} in "{body}"')
    for key, value in data.items():
        if value is None:
            data[key] = {}
    return data


def defined_roles(data):
    """Roles the board really provides: a constant pin that is not NC, or a
    hand-written getter declared in conditional_pins. NC means the board
    deliberately does not have it, so it does not satisfy anything."""
    roles = {r for r, v in data.get('pins', {}).items() if str(v).strip() != 'NC'}
    return roles | set(data.get('conditional_pins', {}))


def _missing(spec, roles, data):
    missing = [r for r in spec.get('requires', []) if r not in roles]
    for group in spec.get('one_of', []):
        if not any(all(r in roles for r in g) for g in spec['one_of']):
            missing.append(' or '.join('+'.join(g) for g in spec['one_of']))
            break
    if 'shared_bus' in spec:
        scalars = data.get('scalars', {})
        bus = scalars.get('MCP2517_BUS', {}).get('value', 'DEFAULT_MCP2517_BUS')
        bus2 = scalars.get('MCP2517_BUS2', {}).get('value', 'DEFAULT_MCP2517_BUS')
        extra = spec['shared_bus'] if bus == bus2 else spec['own_bus']
        missing += [r for r in extra if r not in roles]
    return missing


def validate(board, data):
    roles = defined_roles(data)
    errors = []
    for cap in data.get('capabilities', []):
        if cap not in CAP_SPECS:
            errors.append(f'{board}: unknown capability "{cap}"')
            continue
        for role in _missing(CAP_SPECS[cap], roles, data):
            errors.append(f'{board}: capability "{cap}" needs pin role {role}, '
                          f'which the board does not define')
    seen = set()
    for slot in data.get('can', []):
        name, driver = slot.get('slot'), slot.get('driver')
        if not name or not driver:
            errors.append(f'{board}: CAN entry {slot} needs both slot and driver')
            continue
        if name in seen:
            errors.append(f'{board}: duplicate CAN slot "{name}"')
        seen.add(name)
        if driver not in DRIVER_SPECS:
            errors.append(f'{board}: CAN slot "{name}" has unknown driver "{driver}"')
            continue
        for role in _missing(DRIVER_SPECS[driver], roles, data):
            errors.append(f'{board}: CAN slot "{name}" driver "{driver}" needs pin role '
                          f'{role}, which the board does not define')
    labelled = {}
    for out in data.get('outputs', []):
        if 'label' not in out or 'gpio' not in out:
            errors.append(f'{board}: output {out} needs both label and gpio')
            continue
        if out['gpio'] in labelled:
            errors.append(f'{board}: outputs "{labelled[out["gpio"]]}" and "{out["label"]}" '
                          f'both claim GPIO {out["gpio"]}')
        labelled[out['gpio']] = out['label']
    return errors


def pins_fragment(board, data):
    lines = [PINS_BANNER.format(board=board), '']
    lines.append(f'  const char* name() {{ return "{data["name"]}"; }}')
    lines.append('')
    for role, num in data.get('pins', {}).items():
        lines.append(f'  virtual gpio_num_t {role}() {{ return GPIO_NUM_{num}; }}')
    for name, spec in data.get('scalars', {}).items():
        if not isinstance(spec, dict) or 'type' not in spec or 'value' not in spec:
            raise DeclError(f'{board}: scalar "{name}" needs {{type: ..., value: "..."}}')
        lines.append(f'  virtual {spec["type"]} {name}() {{ return {spec["value"]}; }}')
    return '\n'.join(lines) + '\n'


def caps_fragment(board, data):
    lines = [CAPS_BANNER.format(board=board), '']
    for cap in data.get('capabilities', []):
        lines.append(f'#define BOARD_HAS_{cap.upper()} 1')
    slots = data.get('can', [])
    if slots:
        lines.append('')
        lines.append(f'#define BOARD_CAN_SLOT_COUNT {len(slots)}')
        for driver in sorted({s['driver'] for s in slots}):
            lines.append(f'#define BOARD_HAS_CAN_{driver.upper()} 1')
    outputs = data.get('outputs', [])
    if outputs:
        lines.append('')
        lines.append(f'#define BOARD_LABELLED_OUTPUT_COUNT {len(outputs)}')
        for out in outputs:
            lines.append(f'// {out["label"]}: GPIO {out["gpio"]}'
                         + (f', {out["driver"]}' if 'driver' in out else '')
                         + (f', high at boot' if out.get('boot_state') == 'high' else ''))
    return '\n'.join(lines) + '\n'


def main():
    argv = sys.argv[1:]
    check = '--check' in argv
    boards = Path(argv[argv.index('--boards') + 1]) if '--boards' in argv else BOARDS
    out = Path(argv[argv.index('--out') + 1]) if '--out' in argv else OUT

    files, errors = [], []
    for path in sorted(boards.glob('*.yaml')):
        try:
            data = parse_yaml_subset(path.read_text(encoding='utf-8'), path.name)
            board = data['board']
            board_errors = validate(board, data)
            if board_errors:
                errors += board_errors
                continue
            files.append((out / f'{board}_pins.inc', pins_fragment(board, data)))
            files.append((out / f'{board}_caps.inc', caps_fragment(board, data)))
        except DeclError as exc:
            errors.append(str(exc))

    if errors:
        print('board declaration errors:', file=sys.stderr)
        for err in errors:
            print(f'  {err}', file=sys.stderr)
        sys.exit(1)

    stale = [t for t, text in files
             if not t.exists() or t.read_text(encoding='utf-8') != text]
    if check:
        if stale:
            print('generated fragments are out of date:')
            print('\n'.join(f'  {s}' for s in stale))
            print('run: python3 tools/board_gen.py')
            sys.exit(1)
        print(f'board fragments: up to date ({len(files)} files)')
    else:
        out.mkdir(parents=True, exist_ok=True)
        for target, text in files:
            target.write_text(text, encoding='utf-8')
        print(f'wrote {len(files)} fragments to {out}')


if __name__ == '__main__':
    main()
